Akeaveny/100/cartesian arm control
uwrobotics/uwrt_mars_rover pull request #100
Opened 2020-09-09 21:39 UTC by akeaveny

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
This pr includes a new ros controller that takes in desired velocities on a topic and outputs an array of joint velocities. It does this by generating a kdl tree from our arm's urdf and making calls to kdl to find the desired output velocities.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Here's the underlying algorithm for Cartesian Control.
KDL's IK solver can be found [here](http://docs.ros.org/jade/api/orocos_kdl/html/classKDL_1_1ChainIkSolverVel.html#a761853db487c901485737c6334953cbe) which use's Denavit–Hartenberg parameter's refer to [Modern Robitocs - Appendix C](http://hades.mech.northwestern.edu/images/7/7f/MR.pdf)
![image](https://user-images.githubusercontent.com/56097508/87878649-9dae5b80-c9b3-11ea-87d1-782b8f4b7fae.png)

Launch sequence for testing in Gazebo is similar to [this](https://github.com/uwrobotics/uwrt_mars_rover/tree/somesh/sar/uwrt_arm). 
1. roslaunch uwrt_arm_bringup arm_bringup.launch sim:=true
2. roslaunch uwrt_arm_rover_simulation empty_world.launch
3. rosrun rqt_gui rqt_gui
   3.1 subscribe to **topic:** arm_cartesian_controller/twist_arm_cmds and **type:** uwrt_arm_msgs/UWRTArmTwist @ ~**50hz**
4. rostopic echo /gazebo/link_states

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/56097508/85772345-beec9680-b6ea-11ea-86d8-1d6b630f423b.gif)

2020-09-10 00:40 UTC, wmmc88 requested changes
Is there supposed to be a readme in the uwrt_arm folder. seems like file is empty? 

Seems good. fix the small things I listed. There's still some bloat in the original somesh code but I'll work on cleaning up that sometime

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +    qdot_cart_[5] = 0.0;
```suggestion
    KDL::SetToZero(qdot_cart_);
```
This is better as it is clearer and avoids the lint warnings

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/include/uwrt_cartesian_controller/cartesian_controller.h
> +  ros::Time last_msg_;
```suggestion
  ros::Time last_msg_time_;
```

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +      qdot_cart_[5] = 0.0;
```suggestion
      KDL::SetToZero(qdot_cart_);
```

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +    got_msg_ = false;
should this be true?

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  void UWRTCartesianController::stopping(const ros::Time& time)
```suggestion
  void UWRTCartesianController::stopping(const ros::Time& /*time*/)
```

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  void UWRTCartesianController::starting(const ros::Time& time)
```suggestion
    void UWRTCartesianController::starting(const ros::Time& /*time*/)
```

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  void UWRTCartesianController::update(const ros::Time& time, const ros::Duration& period)
```suggestion
  void UWRTCartesianController::update(const ros::Time& time, const ros::Duration& /*period*/)
```

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/include/uwrt_cartesian_controller/cartesian_controller.h
> +  bool got_msg_;
does this actually get used anywhere?

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +    // ROS_INFO_STREAM("Calling Update!");
debug_stream_named

2020-09-10 00:40 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/uwrt_cartesian_controller_plugins.xml
> +      UWRTCartesianController which accepts TwistStamped Msg.
What does it do? Accepts an End Effector Twist Msg converts it into individual Joint Velocity Cmds

2020-09-17 20:17 UTC, akeaveny commented on uwrt_arm/uwrt_arm/package.xml
> +  <exec_depend>uwrt_arm_controllers</exec_depend>
Now includes 
```
  <exec_depend>uwrt_arm_bringup</exec_depend>
  <exec_depend>uwrt_arm_control</exec_depend>
  <exec_depend>uwrt_arm_controllers</exec_depend>
  <exec_depend>uwrt_arm_description</exec_depend>
  <exec_depend>uwrt_arm_hw</exec_depend>
  <exec_depend>uwrt_arm_msgs</exec_depend>
  <exec_depend>uwrt_arm_rover_simulation</exec_depend>
```

2020-09-17 20:20 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  // ROS_INFO_STREAM("Calling Init!");
deleted

2020-09-17 20:20 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +      ROS_ERROR("Failed to get robot_description parameter");
changed to _robot_description

2020-09-21 00:47 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  nh.param<double>("dead_man_timeout", dead_man_timeout, 0.2);
Yeah, it was from the og repo. I changed this to constexpr double DEFAULT_DEAD_MAN_TIMEOUT{0.2}.

2020-09-21 01:35 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/include/uwrt_cartesian_controller/cartesian_controller.h
> +  bool got_msg_;
Nope, I removed it

2020-09-21 01:37 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +    got_msg_ = false;
I removed the got_msg_ flag

2020-09-21 01:44 UTC, akeaveny commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  // NOLINTNEXTLINE(cppcoreguidelines-owning-memory)
I replaced this with std::unique_ptr but still have an error w/o a NOLINTNEXTLINE

```
error: initializing non-owner argument of type 'std::unique_ptr<KDL::ChainIkSolverVel, std::default_delete<KDL::ChainIkSolverVel> >::pointer' (aka 'KDL::ChainIkSolverVel *') with a newly created 'gsl::owner<>' [cppcoreguidelines-owning-memory,-warnings-as-errors]
  cart_to_joint_solver_vel_.reset(new KDL::ChainIkSolverVel_pinv(kdl_chain_));
```

2020-09-21 01:50 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  nh.param<double>("dead_man_timeout", dead_man_timeout, 0.2);
put a TODO or FIXME to change the timeout to be maybe configurable in a cfg file. someone needs to add one of these to the drivetrain too

2020-09-21 02:18 UTC, wmmc88 commented on uwrt_arm/uwrt_arm_controllers/uwrt_cartesian_controller/src/cartesian_controller.cpp
> +  // NOLINTNEXTLINE(cppcoreguidelines-owning-memory)
hmm it shouldn't. could u push with the change? it might be a bug in the linter then....

2024-05-20 20:19 UTC, closed without merging